<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>OpenAgent.Core.Tests</AssemblyName>
    <RootNamespace>OpenAgent.Core.Tests</RootNamespace>
    <NoWarn>$(NoWarn);MAAI001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xunit.SkippableFact" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenAgent.Authorization\OpenAgent.Authorization.csproj" />
    <ProjectReference Include="..\..\src\OpenAgent.Core\OpenAgent.Core.csproj" />
  </ItemGroup>

</Project>
