<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>OpenAgent.Contracts.Tests</AssemblyName>
    <RootNamespace>OpenAgent.Contracts.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenAgent.Authorization\OpenAgent.Authorization.csproj" />
    <ProjectReference Include="..\..\src\OpenAgent.Contracts\OpenAgent.Contracts.csproj" />
  </ItemGroup>

</Project>
