<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OpenAgent.Engine.Tests" />
    <InternalsVisibleTo Include="OpenAgent.Engine.Host" />
    <InternalsVisibleTo Include="OpenAgent.TestFramework" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.9.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Agent.Core\src\Core\OpenAgent.Core.csproj" />
  </ItemGroup>

</Project>
