<script setup lang="ts">
import type { useModelSettings } from './useModelSettings'

const props = defineProps<{ context: ReturnType<typeof useModelSettings> }>()
const { llmDraft, llmResult, testingLlm, savingLlm, showLlmEditor, isNewLlm, saveLlm, testLlm } = props.context
</script>

<template>
  <el-dialog v-model="showLlmEditor" class="editor-dialog" modal-class="editor-overlay" :title="isNewLlm ? '新增大模型配置' : '编辑大模型配置'" width="min(720px, calc(100vw - 32px))" append-to-body destroy-on-close>
    <el-form label-position="top" class="agent-form-grid"><el-form-item label="配置 ID"><el-input v-model="llmDraft.id" :disabled="!isNewLlm" placeholder="例如 openai-gpt4o" /><small class="form-help">执行请求通过这个 ID 选择模型配置。</small></el-form-item><el-form-item label="显示名称"><el-input v-model="llmDraft.name" placeholder="例如 OpenAI GPT-4o" /></el-form-item><el-form-item label="模型 ID"><el-input v-model="llmDraft.modelId" placeholder="例如 gpt-4o" /></el-form-item><el-form-item label="模型能力"><el-select v-model="llmDraft.modality" class="full-width"><el-option label="文本" value="Text" /><el-option label="多模态（当前仅图片）" value="Multimodal" /></el-select><small class="form-help">多模态模型会将受限大小的图片直接发送给模型；音频、视频等输入暂不开放。</small></el-form-item><el-form-item label="上下文大小"><el-input-number v-model="llmDraft.contextTokens" :min="1" :step="1024" controls-position="right" /><small class="form-help">模型可接受的最大上下文 token 数。</small></el-form-item><el-form-item label="API 格式"><el-select v-model="llmDraft.format" class="full-width"><el-option label="OpenAI Chat Completions" value="OpenAIChatCompletions" /><el-option label="OpenAI Responses" value="OpenAIResponses" /><el-option label="Anthropic Messages" value="AnthropicMessages" /></el-select></el-form-item><el-form-item label="Temperature"><el-input-number v-model="llmDraft.temperature" :min="0" :max="2" :step="0.1" :precision="1" controls-position="right" /></el-form-item><el-form-item label="Endpoint" class="span-two"><el-input v-model="llmDraft.endpoint" placeholder="https://api.openai.com/v1" /></el-form-item><el-form-item label="API Key" class="span-two"><el-input v-model="llmDraft.apiKey" type="password" show-password autocomplete="new-password" placeholder="编辑时留空表示保留现有密钥" /><small class="form-help">密钥在服务端加密保存，但查询响应永不返回；测试会使用已保存的真实密钥。</small></el-form-item><el-alert v-if="llmResult" class="span-two" :title="`测试结果：${llmResult.success ? '连接和权限通过' : '连接失败'}${llmResult.statusCode ? ` · HTTP ${llmResult.statusCode}` : ''}`" :description="llmResult.error || `模型 ${llmResult.modelId || llmDraft.modelId} · 延迟 ${llmResult.latencyMs}ms`" :type="llmResult.success ? 'success' : 'warning'" :closable="false" /></el-form>
    <template #footer><el-button @click="showLlmEditor = false">取消</el-button><el-button :loading="testingLlm" @click="testLlm">测试连接与权限</el-button><el-button type="primary" :loading="savingLlm" :disabled="!llmDraft.id" @click="saveLlm">保存大模型配置</el-button></template>
  </el-dialog>
</template>
